# Generated by Django 5.2.1 on 2025-05-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
