# Generated by Django 5.2.1 on 2025-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ex_date', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=10, verbose_name=[('milk', 'milk'), ('chips', 'chips'), ('candy', 'candy')])),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
